### ISSUE TITLE
Does this work with fish shell?

### ISSUE THREAD

**Issue by mren** [alecthomas/ondir#1]
I just found out about this little gem.
From reading the Readme it seems to work with bash or tcsh.
Does ondir also works with the [fish shell](http://fishshell.com/)

**Comment by alecthomas** [comment]
I don't know anything about fish, but apart from the directory changing hook scripts, ondir is shell agnostic. It basically just outputs text to stdout based on which enter/leave events match the directories traversed.

You can try this yourself by making a trivial `~/.ondirrc` file like this:

``` bash
enter ~
  echo Home sweet home
```

And then typing:

``` bash
cd ~ && ondir /
```

A quick Google shows that Fish has some kind of event system that could probably be used to drive ondir. I'd welcome a pull request if you get it working!

Try something like this:

``` fish
function -e fish_prompt ondir_prompt_hook
  if test -e "$OLDONDIRWD"
    set -g OLDONDIRWD /
  end
  if [ "$OLDONDIRWD" != "$PWD" ]
    ondir $OLDONDIRWD $PWD
  end
  set -g OLDONDIRWD "$PWD"
end
```

Let me know if that works/doesn't work.

**Comment by mren** [comment]
Thanks for the good feedback.

``` bash
function ondir_prompt_hook --on-event fish_prompt
    if test ! -e "$OLDONDIRWD"
                set -g OLDONDIRWD /
        end
        if [ "$OLDONDIRWD" != "$PWD" ]
                ondir $OLDONDIRWD $PWD
        end
        set -g OLDONDIRWD "$PWD"
end
```

had to negate the first statement and made the -e flag more explicit.
The script works.

Although ondir is giving me some problems.

``` bash
$ cat .ondirrc 
enter ~
  echo "Home sweet home"
enter ~/Documents
    ls
$ cd /
$ cd ~
echo "Home sweet home"
$ cd Documents/
ls
```

The commands in the `.ondirrc` are just printed to the terminal and not executed.
I expected this is an issue with ondir and fish, but all other shells behave the same way

``` bash
$ bash
bash-3.2$ ondir / ~
echo "Home sweet home"
bash-3.2$ sh
sh-3.2$ ondir / ~
echo "Home sweet home"
sh-3.2$ zsh% ondir / ~
echo "Home sweet home"
```

Is my `.ondirrc` correct?

I try to provide you as much info as possible.

I'm running Mac OS X 10.8.5 with terminal.app and fish, zsh and ondir installed via homebrew

``` bash
% ondir -V
This is OnDir version 0.2.3
% bash --version
GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin12)
Copyright (C) 2007 Free Software Foundation, Inc.
% fish -v
fish, version 2.0.0
% zsh --version
zsh 4.3.11 (i386-apple-darwin12.0)
```

**Comment by alecthomas** [comment]
Sorry, my bad. You need to somehow eval the output of ondir. In bash it would be eg. `eval $(ondir /)`. I don't know what the equivalent in fish is, but I imagine it has some mechanism.

**Comment by mren** [comment]
Haha nice. I like the elegance in this.

Ok I updated the fish script

``` bash
function ondir_prompt_hook --on-event fish_prompt
        if test ! -e "$OLDONDIRWD"; set -g OLDONDIRWD /; end;
        if [ "$OLDONDIRWD" != "$PWD" ]; eval (ondir $OLDONDIRWD $PWD); end;
        set -g OLDONDIRWD "$PWD";
end
```

Do you want to add this yourself or should I create a Pull Request for you?

**Comment by alecthomas** [comment]
Very nice! If you could send a Pull Request that would be awesome.

**Comment by mren** [comment]
sure thing. I will create a Pull Request.
