### ISSUE TITLE
call leave on exit command

### ISSUE THREAD

**Issue by sumanthratna** [alecthomas/ondir#10]
I would like the following (I use `zsh`):
1. `cd` into a directory and run a certain command (for example, `vagrant resume`). 
2. when I'm done working in the directory, by habit I typically just `exit` to leave the terminal. However, this doesn't `vagrant suspend`, which I need to do. thus, if the contents of `leave` were called on `exit`, it would do exactly what I'd like

I think this could help a handful of people but I have no idea how this could be implemented. 

**EDIT**: If there's somehow a way to figure out when the `exit` command is called, then implementing should be simple (just call `ondir`). I think looking into the actual `leave` command (see `man leave`) could be helpful.

**EDIT**: Looking at the [source code](https://github.com/freebsd/freebsd/blob/master/usr.bin/leave/leave.c), `leave` doesn't seem too helpful, but maybe [these lines](https://github.com/freebsd/freebsd/blob/master/usr.bin/leave/leave.c#L173-L174) might help?

**Comment by alecthomas** [comment]
I think you should just be able to do something like this:

```
trap 'ondir $PWD /' EXIT
```
