### ISSUE TITLE
Allow ondirrc to be located in non-home directory

### ISSUE THREAD

**Issue by sumanthratna** [alecthomas/ondir#11]
For example, being able to have `.ondirrc` in a `dotfiles` repository would be useful. Perhaps in `.zshrc` (or the equivalent) allow the user to run `ondir --config ~/.dotfiles/.ondirrc`, which would refer to `~/.dotfiles/.ondirrc` for the rest of the terminal session.

**Comment by alecthomas** [comment]
`dotfiles` directories typically have a way to symlink into other locations, but if you'd like to submit a PR...

**Comment by sumanthratna** [comment]
I can't believe I forgot about `symlink`ing the file. I don't think there's a need to implement this feature.
