### ISSUE TITLE
Maintenance / Alternatives ?

### ISSUE THREAD

**Issue by Neirda24** [alecthomas/ondir#13]
Hi !

This is a super useful yet simple tool. Although the fact that it has not be actively maintained worries me a bit. Is there a plan for maintenance or alternatives you might know / use ?

Thanks.

**Comment by smartmic** [comment]
Hm, why are you worried, are you facing any issues? The tool is really simple (and I mean that in the most positive sense) so there are good reasons to assume it is feature complete and does not need active maintance. I do not have the expectation that such kind of software breaks every few months.

**Comment by Neirda24** [comment]
I didn't used it for some time now so I'll have to try again to give more input but from what I remember it lacks some features, there are some bugs I've encountered. Again without a daily usage of this I don't have anything concrete to give you right now. Either way the topic I opened is relative to maintenance for such cases. In case it is not maintained anymore I wondered if there was some good alternatives.

**Comment by smartmic** [comment]
Okay, thanks for clarification. Hopefully bugs will be looked at if posted here. Concerning alternatives, I think one way is to write your own shell function for `cd` or there is also [direnv](https://direnv.net/). I do not use it, so I cannot say anything about its usability.

**Comment by Neirda24** [comment]
Yeah, I've looked at direnv but it looks at a .env file (which I already use for other purposes. Or need a custom file which I prefer to avoid. Also ondir was able to run custom script which is exactly what I'm looking for. for the cd function it doesn't comply with the "Leaving directory" feature of ondir.

**Comment by alecthomas** [comment]
I mean, if there are bugs, file an issue. I use ondir every day and don't have any issues, but YMMV.
