### ISSUE TITLE
ondir hangs for specific config and input

### ISSUE THREAD

**Issue by rpost** [alecthomas/ondir#14]
Hi

Given:

```
enter /home/radek/code
  echo "entering code"
leave /home/radek/code
  echo "leaving code"
```

config when I run `ondir /home/radek /home/radek/code/test` program hangs (and keeps printing `echo "entering code"`)

What is interesting when I change `radek` to `rdek` everything works as expected. Doesn't ondir like my name? :smile:

**Comment by alecthomas** [comment]
What version are you on?

**Comment by alecthomas** [comment]
I can't replicate this FWIW 🤔

**Comment by alecthomas** [comment]
```
~ $ ondir /home/radek /home/radek/code/test
echo "entering code"
```

**Comment by rpost** [comment]
please have a look: https://asciinema.org/a/HDdivmUBY7OljIShxjAgWbQHY
