### ISSUE TITLE
fish: multiline commands fails

### ISSUE THREAD

**Issue by qfox** [alecthomas/ondir#4]
```
$ ondir ~/ ~/repos/repo
if [ -z (git config --local user.email) ]
git config user.email user@example.org
end
```

But when I calling this from fish:

```
$ echo (ondir ~/ ~/repos/repo)
if [ -z (git config --local user.email) ] git config user.email user@example.org end
```

I suggest to add `| tr '\n' ';'` here: https://github.com/alecthomas/ondir/blob/master/ondir_prompt_hook.fish#L4

**Comment by alecthomas** [comment]
I don't know anything about fish, but ondir just outputs whatever is in the configuration file. A quick Google search comes up with [this issue](https://github.com/fish-shell/fish-shell/issues/159) from the fish-shell project, which is probably the root problem? I think substituting `;` for `\n` is probably not robust, but I don't have a better suggestion.

**Comment by alecthomas** [comment]
PS. The obvious (but not ideal) solution is to include `;` in your `.ondirrc`.
