### ISSUE TITLE
redefining builtins functions seem not taking place

### ISSUE THREAD

**Issue by albasili** [alecthomas/ondir#6]
I have installed the tool, taken the shell script and included in my ``.bashrc``, created a very simple ``ondirrc`` file, but nothing works as expected.

Whenever I enter the configured folder, I don't get to ``echo`` message I expected. Whenever I leave the configured folder, same behavior.

If I **am** in the configured folder and I source my .bashrc, I get the ``echo`` message, but then again if I leave it, nothing happens.

What am I doing wrong? It seems to me the functions ``cd``, ``pushd`` and ``popd`` are not remapped as intended.

**Comment by alecthomas** [comment]
Are you sourcing the shell script? eg. `source <script>`? You have to source it, not execute it.

**Comment by albasili** [comment]
Yep! My bad, I overlooked it.
Thanks loads, very nice tool!
