### ISSUE TITLE
Tarball for 0.2.3

### ISSUE THREAD

**Issue by Moiman** [alecthomas/ondir#7]
Hello is there tarball for ondir-0.2.3 ??

**Comment by ilovezfs** [comment]
@Moiman there's
https://swapoff.org/files/ondir/ondir-0.2.3.tar.gz
and even
https://swapoff.org/files/ondir/ondir-0.2.4.tar.gz

@alecthomas why does https://swapoff.org/ondir.html show only 0.2.2 if the latest tarball is 0.2.4?

**Comment by moggers87** [comment]
This could be solved by tagging releases in git and github will populate automatically https://github.com/alecthomas/ondir/releases
