### ISSUE TITLE
Hang on sub-directory navigation

### ISSUE THREAD

**Issue by dawesc** [alecthomas/ondir#8]
My config looks as follows:
<pre>
chrisd@clap-ubuntu:~$ cat .ondirrc 
enter ~/git
  export PREFIX=/usr/local/bp
  export LD_LIBRARY_PATH=.:/usr/local/bp/lib
  echo "Using PREFIX $PREFIX"

leave ~/git
  export PREFIX=

enter ~/git_develop
  export PREFIX=/usr/local/bp_develop
  export LD_LIBRARY_PATH=.:/usr/local/bp_develop/lib
  echo "Using PREFIX $PREFIX"

leave ~/git_develop
  export PREFIX=
  export LD_LIBRARY_PATH=

chrisd@clap-ubuntu:~$ 
</pre>

However when i try to navigate to a sub-folder it hangs:
<pre>
chrisd@clap-ubuntu:~$ cd
chrisd@clap-ubuntu:~$ cd git/BP.Node
^C
chrisd@clap-ubuntu:~/git/BP.Node$ 
</pre>

When navigating directly it doesn't:
<pre>
chrisd@clap-ubuntu:~$ cd git
Using PREFIX /usr/local/bp
chrisd@clap-ubuntu:~/git$ cd BP.Node/
chrisd@clap-ubuntu:~/git/BP.Node$
</pre>

Any help appreciated. Thanks for the great app, christopher

**Comment by dawesc** [comment]
Backtrace during hang is:
<pre>
(gdb) bt
#0  0x00007f63ffeb050f in _int_malloc (av=av@entry=0x7f6400207c40 <main_arena>, bytes=bytes@entry=88)
    at malloc.c:3721
#1  0x00007f63ffeb60b1 in __libc_calloc (n=n@entry=88, elem_size=elem_size@entry=1) at malloc.c:3436
#2  0x00007f63fff104cb in create_cd_newstate (hash=5, context=0, nodes=0x7ffdd67a4ad0, dfa=0x55cf4c3dd0c0)
    at regex_internal.c:1659
#3  re_acquire_state_context (err=err@entry=0x7ffdd67a4acc, dfa=dfa@entry=0x55cf4c3dd0c0, 
    nodes=nodes@entry=0x7ffdd67a4ad0, context=context@entry=0) at regex_internal.c:1534
#4  0x00007f63fff1125a in build_trtable (dfa=<optimised out>, state=state@entry=0x55cf559c1160)
    at regexec.c:3361
#5  0x00007f63fff1c0b8 in transit_state (state=0x55cf559c1160, mctx=0x7ffdd67a4c80, err=0x7ffdd67a4c3c)
    at regexec.c:2251
#6  check_matching (p_match_first=0x7ffdd67a4c38, fl_longest_match=1, mctx=0x7ffdd67a4c80) at regexec.c:1118
#7  re_search_internal (preg=preg@entry=0x7ffdd67a4e00, string=string@entry=0x7ffdd67a5160 "/home/chrisd/git", 
    length=16, start=<optimised out>, start@entry=0, range=<optimised out>, stop=<optimised out>, 
    nmatch=18446744073709551608, pmatch=0x7ffdd67a5100, eflags=0) at regexec.c:790
#8  0x00007f63fff1d72a in __GI___regexec (preg=0x7ffdd67a4e00, string=0x7ffdd67a5160 "/home/chrisd/git", 
    nmatch=<optimised out>, pmatch=0x7ffdd67a5100, eflags=0) at regexec.c:220
#9  0x000055cf4c162514 in ?? ()
#10 0x000055cf4c1627de in ?? ()
#11 0x000055cf4c161765 in ?? ()
#12 0x00007f63ffe3db97 in __libc_start_main (main=0x55cf4c161130, argc=3, argv=0x7ffdd67a7298, 
    init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7ffdd67a7288)
    at ../csu/libc-start.c:310
#13 0x000055cf4c16184a in ?? ()
(gdb) thread apply all bt

Thread 1 (process 7485):
#0  0x00007f63ffeb050f in _int_malloc (av=av@entry=0x7f6400207c40 <main_arena>, bytes=bytes@entry=88) at malloc.c:3721
#1  0x00007f63ffeb60b1 in __libc_calloc (n=n@entry=88, elem_size=elem_size@entry=1) at malloc.c:3436
#2  0x00007f63fff104cb in create_cd_newstate (hash=5, context=0, nodes=0x7ffdd67a4ad0, dfa=0x55cf4c3dd0c0) at regex_internal.c:1659
#3  re_acquire_state_context (err=err@entry=0x7ffdd67a4acc, dfa=dfa@entry=0x55cf4c3dd0c0, nodes=nodes@entry=0x7ffdd67a4ad0, context=context@entry=0) at regex_internal.c:1534
#4  0x00007f63fff1125a in build_trtable (dfa=<optimised out>, state=state@entry=0x55cf559c1160) at regexec.c:3361
#5  0x00007f63fff1c0b8 in transit_state (state=0x55cf559c1160, mctx=0x7ffdd67a4c80, err=0x7ffdd67a4c3c) at regexec.c:2251
#6  check_matching (p_match_first=0x7ffdd67a4c38, fl_longest_match=1, mctx=0x7ffdd67a4c80) at regexec.c:1118
#7  re_search_internal (preg=preg@entry=0x7ffdd67a4e00, string=string@entry=0x7ffdd67a5160 "/home/chrisd/git", length=16, start=<optimised out>, start@entry=0, 
    range=<optimised out>, stop=<optimised out>, nmatch=18446744073709551608, pmatch=0x7ffdd67a5100, eflags=0) at regexec.c:790
#8  0x00007f63fff1d72a in __GI___regexec (preg=0x7ffdd67a4e00, string=0x7ffdd67a5160 "/home/chrisd/git", nmatch=<optimised out>, pmatch=0x7ffdd67a5100, eflags=0) at regexec.c:220
#9  0x000055cf4c162514 in ?? ()
#10 0x000055cf4c1627de in ?? ()
#11 0x000055cf4c161765 in ?? ()
#12 0x00007f63ffe3db97 in __libc_start_main (main=0x55cf4c161130, argc=3, argv=0x7ffdd67a7298, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, 
    stack_end=0x7ffdd67a7288) at ../csu/libc-start.c:310
#13 0x000055cf4c16184a in ?? ()
(gdb) 
</pre>

**Comment by dawesc** [comment]
oooo scary, ok when i compile and install the version from git all is well :o guess it's a problem with ubuntu 18.04 version of this:

<pre>
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  ondir          0.2.3+git0.5 amd64        Automate tasks specific to certai
chrisd@clap-ubuntu:~/git/BP.Node$ 
</pre>

Sorry to bother and thanks agan!

**Comment by alecthomas** [comment]
👍
