### ISSUE TITLE
Support ~ expansion in folder names

### ISSUE THREAD

**Issue by martinpaljak** [alecthomas/ondir#9]
So that an .ondirrc file could be portable between Linux and macOS

**Comment by alecthomas** [comment]
It does! Here's a sample from my config:

```sh
enter ~/Projects/([^/]+)
  git() {
    /usr/local/bin/hub "$@"
  }
```

**Comment by martinpaljak** [comment]
Hmm. Indeed. What could be the reason of it not working on a certain machine, and only working with full paths?

**Comment by alecthomas** [comment]
Did this happen with a regex? IIRC it will only do path expansion if the ~ is at the beginning of the path.

**Comment by martinpaljak** [comment]
Yep, the problem was double space:`leave<space><space>~/some/folder`. Removing the extra space made it work. I'd thus suggest the path to be trimmed before matching
